server:
  port: ${PORT:8080}

spring:
  application:
    name: suspect_registry-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED:true}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:suspect_registry}
    prefer-ip-address: false
    instance-id: ${EUREKA_INSTANCE_HOSTNAME:suspect_registry}:${PORT:8080}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
