server:
  port: ${PORT:8080}

spring:
  application:
    name: suspect-registry-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:suspect-registry}
    prefer-ip-address: false
    instance-id: ${EUREKA_INSTANCE_HOSTNAME:suspect-registry}:${PORT:8080}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

aws:
  region: ${AWS_REGION:us-east-1}
  sqs:
    suspectRequestsQueueUrl: ${SUSPECT_REQUESTS_QUEUE_URL:}
    suspectEventsQueueUrl: ${SUSPECT_EVENTS_QUEUE_URL:}

encryption:
  key: ${ENCRYPTION_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
