server:
  port: ${PORT:8080}
  shutdown: graceful

spring:
  application:
    name: identity-auth-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finsight}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  lifecycle:
    timeout-per-shutdown-phase: 20s

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      platform: postgres
      continue-on-error: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.finsight: INFO
