-- ===========================
-- Identity/Auth Service Schema
-- ===========================

CREATE TABLE IF NOT EXISTS role (
  role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS app_user (
  user_id UUID PRIMARY KEY,
  email VARCHAR(320) NOT NULL UNIQUE,
  password_hash VARCHAR(255), -- nullable for OAuth-only
  first_name VARCHAR(64),
  last_name VARCHAR(64),
  phone VARCHAR(32),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  role_id INT NOT NULL REFERENCES role(role_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS oauth_identity (
  oauth_id BIGSERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
  provider VARCHAR(32) NOT NULL,
  provider_user_id VARCHAR(256) NOT NULL,
  email_at_provider VARCHAR(320),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_user_id)
);

-- Seed roles (safe upsert-style)
INSERT INTO role(role_name) VALUES ('INVESTIGATOR') ON CONFLICT DO NOTHING;
INSERT INTO role(role_name) VALUES ('SUPERVISOR') ON CONFLICT DO NOTHING;
INSERT INTO role(role_name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
