server:
  port: ${PORT:8080}

spring:
  application:
    name: documents-cases-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finsight}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      platform: postgres
      continue-on-error: false

aws:
  region: ${AWS_REGION:us-east-1}

  dynamodb:
    endpoint: ${DDB_ENDPOINT:}

  sqs:
    caseQueueUrl: ${CASE_QUEUE_URL:}

  s3:
    bucket: ${DOCS_BUCKET:finsight-docs}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.finsight: INFO
