server:
  port: ${PORT:8080}

spring:
  application:
    name: documents-cases-service
  cloud:
    compatibility-verifier:
      enabled: false
  
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:25MB}
      max-request-size: ${MAX_REQUEST_SIZE:25MB}

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/finsight_documents}
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: never
      platform: mysql
      continue-on-error: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false

aws:
  region: ${AWS_REGION:us-east-1}

  dynamodb:
    endpoint: ${DDB_ENDPOINT:}

  sqs:
    caseQueueUrl: ${CASE_QUEUE_URL:}

  s3:
    bucket: ${DOCS_BUCKET:finsight-documents-2026}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.finsight: INFO
